//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.25 at 09:57:53 PM MSK 
//


package web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cyanColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="magentaColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="yellowColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="blackColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cyanColor",
    "magentaColor",
    "yellowColor",
    "blackColor"
})
@XmlRootElement(name = "ColorStringRequest")
public class ColorStringRequest {

    protected String cyanColor;
    protected String magentaColor;
    protected String yellowColor;
    protected String blackColor;

    /**
     * Gets the value of the cyanColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCyanColor() {
        return cyanColor;
    }

    /**
     * Sets the value of the cyanColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCyanColor(String value) {
        this.cyanColor = value;
    }

    /**
     * Gets the value of the magentaColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMagentaColor() {
        return magentaColor;
    }

    /**
     * Sets the value of the magentaColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMagentaColor(String value) {
        this.magentaColor = value;
    }

    /**
     * Gets the value of the yellowColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYellowColor() {
        return yellowColor;
    }

    /**
     * Sets the value of the yellowColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYellowColor(String value) {
        this.yellowColor = value;
    }

    /**
     * Gets the value of the blackColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlackColor() {
        return blackColor;
    }

    /**
     * Sets the value of the blackColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlackColor(String value) {
        this.blackColor = value;
    }

}
