//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.24 at 01:54:19 PM MSK 
//


package web_service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cyan" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="magenta" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="yellow" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="black" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cyan",
    "magenta",
    "yellow",
    "black"
})
@XmlRootElement(name = "ColorRequest")
public class ColorRequest {

    protected boolean cyan;
    protected boolean magenta;
    protected boolean yellow;
    protected boolean black;

    /**
     * Gets the value of the cyan property.
     * 
     */
    public boolean isCyan() {
        return cyan;
    }

    /**
     * Sets the value of the cyan property.
     * 
     */
    public void setCyan(boolean value) {
        this.cyan = value;
    }

    /**
     * Gets the value of the magenta property.
     * 
     */
    public boolean isMagenta() {
        return magenta;
    }

    /**
     * Sets the value of the magenta property.
     * 
     */
    public void setMagenta(boolean value) {
        this.magenta = value;
    }

    /**
     * Gets the value of the yellow property.
     * 
     */
    public boolean isYellow() {
        return yellow;
    }

    /**
     * Sets the value of the yellow property.
     * 
     */
    public void setYellow(boolean value) {
        this.yellow = value;
    }

    /**
     * Gets the value of the black property.
     * 
     */
    public boolean isBlack() {
        return black;
    }

    /**
     * Sets the value of the black property.
     * 
     */
    public void setBlack(boolean value) {
        this.black = value;
    }

}
