//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.25 at 09:57:53 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "web-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package web_service;
